version: '3.8'
name: planthor-webapi-ws

services:
  planthorwebapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/planthorwebapi:cached
      - "${HOME}/Library/Application Support/Code/User:/home/vscode/.local/share/code/user:cached"
    command: sleep infinity
    user: vscode
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
